### PR TITLE
Kitsu: Update kitsu addon docs to match kitsu addon version 1.1.0

### PR DESCRIPTION
**Pull request by MustafaJafar**
# Changelog description
Update Kitsu addon docs to 1.1.0

### CODE REVIEW

**Comment by MustafaJafar** [comment]
I was testing Kitsu while writing docs. 
These were my testing notes: 
- `entities_naming_pattern` are no longer used.
- Kitsu plugins doesn't work with Houdini. I was able to make it work by adding `review` to `families` as @BigRoy suggested [here](https://community.ynput.io/t/publishing-houdini-preview-in-kitsu-through-openpype/560/4)
- `custom comment template` (minified markdown doesn't work on my kitsu. but a mix between markdown and `\n` worked).
- `IntegrateKitsuNote` settings are not applied. (I was able to get screenshots in this PR by modifying `IntegrateKitsuNote` class attributes)
- `IntegrateKitsuNote` logic is hard for me. especially `family_requirements` and the fact it's a `Context Plugin`

**Comment by mkolar** [comment]
> Reference

Best to add as issues to [ynput/ayon-kitsu](https://github.com/ynput/ayon-kitsu)

**Comment by HannahFantasia** [comment]
I feel like this is a huge improvement from the existing docs already. Thanks a lot Mustafa!

What would be nice is to have something that when filling in the IP, that it would address this as well:
https://community.ynput.io/t/kitsu-connection-error-could-not-login-to-kitsu/1556

Or have basic networking knowledge as a per-requisite. ;-)

**Review by kalisp — APPROVED** [review]
Yes, these are much better than published. Lets merge it and update later.

**Pull request merged**
